package com.hibernate;

// Generated Jun 1, 2015 9:41:50 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BookedFlight generated by hbm2java
 */
@Entity
@Table(name = "booked_flight", catalog = "flightservice")
public class BookedFlight implements java.io.Serializable {

	private int flightId;
	private int availableSeat;
	private int capacity;
	private Set<UserFlight> userFlights = new HashSet<UserFlight>(0);

	public BookedFlight() {
	}

	public BookedFlight(int flightId, int availableSeat, int capacity) {
		this.flightId = flightId;
		this.availableSeat = availableSeat;
		this.capacity = capacity;
	}

	public BookedFlight(int flightId, int availableSeat, int capacity,
			Set<UserFlight> userFlights) {
		this.flightId = flightId;
		this.availableSeat = availableSeat;
		this.capacity = capacity;
		this.userFlights = userFlights;
	}

	@Id
	@Column(name = "flight_id", unique = true, nullable = false)
	public int getFlightId() {
		return this.flightId;
	}

	public void setFlightId(int flightId) {
		this.flightId = flightId;
	}

	@Column(name = "available_seat", nullable = false)
	public int getAvailableSeat() {
		return this.availableSeat;
	}

	public void setAvailableSeat(int availableSeat) {
		this.availableSeat = availableSeat;
	}

	@Column(name = "capacity", nullable = false)
	public int getCapacity() {
		return this.capacity;
	}

	public void setCapacity(int capacity) {
		this.capacity = capacity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bookedFlight")
	public Set<UserFlight> getUserFlights() {
		return this.userFlights;
	}

	public void setUserFlights(Set<UserFlight> userFlights) {
		this.userFlights = userFlights;
	}

}
