package com.hibernate;

// Generated Jun 1, 2015 9:41:50 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserFlight generated by hbm2java
 */
@Entity
@Table(name = "user_flight", catalog = "flightservice")
public class UserFlight implements java.io.Serializable {

	private Integer userFlightId;
	private BookedFlight bookedFlight;
	private User user;
	private String origin;
	private String destination;

	public UserFlight() {
	}

	public UserFlight(BookedFlight bookedFlight, User user, String origin,
			String destination) {
		this.bookedFlight = bookedFlight;
		this.user = user;
		this.origin = origin;
		this.destination = destination;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_flight_id", unique = true, nullable = false)
	public Integer getUserFlightId() {
		return this.userFlightId;
	}

	public void setUserFlightId(Integer userFlightId) {
		this.userFlightId = userFlightId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "flight_id", nullable = false)
	public BookedFlight getBookedFlight() {
		return this.bookedFlight;
	}

	public void setBookedFlight(BookedFlight bookedFlight) {
		this.bookedFlight = bookedFlight;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "origin", nullable = false, length = 45)
	public String getOrigin() {
		return this.origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

	@Column(name = "destination", nullable = false, length = 45)
	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

}
